#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     FR,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     BR,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     scooper,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     FL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     claw,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    Lscooperangle,        tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    Rscooperangle,        tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    stopper,              tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"
task main()
{
	float a;
	float b;
  float c;
  float d;
  float e;
  float rangle = 255;
  float langle = 0;

	while(1)
	{
		a= joystick.joy1_y1;
		b= joystick.joy1_y2;
	  c= joystick.joy1_x2;
	  d= rangle;
	  e= langle;

	  //Wheel motors
	 	if(a<10 && a>-10)
		{
			motor[FL]=0;
			motor[BL]=0;
		}
		else
		{
			motor[FL]=a;
			motor[BL]=a;
		}
		if(b<10 && b>-10)
		{
			motor[FR]=0;
			motor[BR]=0;
		}
		else
		{
			motor[FR]=b;
			motor[BR]=b;
		}

		//Lift motors
		if(joy1Btn(3)==1 && joy1Btn(1)==0)
		{
     motor[lift]=100;
		}
		else if(joy1Btn(3)==0 &&joy1Btn(1)==1)
		{
			motor[lift]=-100;
		}
		else
		{
			motor[lift]=0;
		}

		//Claw motor
		if(joy1Btn(10)== 1)
		{
			motor[claw]=100;
		}
		else if(joy1Btn(10)== 0)
		{
			motor[claw]=0;
		}

		//Scooper
		if(joy1Btn(7) == 1 && joy1Btn(8) == 0)
		{
			motor[scooper]=100;
		}
		else if(joy1Btn(7) == 0 && joy1Btn(8) == 1)
		{
			motor[scooper]=-100;
		}
		else
		{
			motor[scooper]=0;
		}

		//Lift stop
		if(c<=10)
	 	{
	   	servo[stopper]= 0;
		}
		else if(c>10)
		{
			servo[stopper]=255;
		}

		//Scooper angle
		if(joy1Btn(2) == 1 && joy1Btn(4) == 0)
		{
	   rangle += .5;
		}
		else if(joy1Btn(4) == 1 && joy1Btn(2) == 0)
		{
		 langle -= .5;
		}

	if(langle < 0)
		langle = 0;
	else if(langle > 255)
		langle = 255;
	if(rangle < 0)
		rangle = 0;
	else if(rangle > 255)
		rangle = 255;

	servo[Lscooperangle] = (int)langle;
	servo[Rscooperangle] = (int)(255-rangle);

	}
}
//KAPPA
