#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     topPulley,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     bottomPulley,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     bucket,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     arm,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     leftBack,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     leftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     rightFront,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     rightBack,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_1,     empty1,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     empty1,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    guard,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    rightGrabber,         tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    leftGrabber,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,         	      tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,                tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.



bool guardUp = true;

int threshold = 6;



int slownessFactor = 2;



int rightServoUp = 0;

int rightServoDown= 140;

int leftServoUp = 150;

int leftServoDown= 0;



int j1y1 = 0;

int j1y2 = 0;

int j1x1 = 0;

int j2y1 = 0;



void initializeRobot(){

	getJoystickSettings(joystick);

	//servo[rightGrabber] = rightServoUp;

	//servo[leftGrabber] = leftServoUp;

	return;

}

void getJoystickValues(){

	j1y1 = -joystick.joy1_y1; //this is for drive]

	j1y2 = joystick.joy1_y2;  //this is for the lift

	j1x1 = -joystick.joy1_x1; //this is for drive

	j2y1 = joystick.joy2_y1;  //this is for the lift

}



void arcadeDrive(){

	if((j1x1 > threshold || j1x1< -threshold) || (j1y1 > threshold || j1y1< -threshold)){

		//	if((j1x1 <= 63 && j1y1 <= 63) && (j1x1 >= -63 && j1y1 >= -63)){ //slows down for precision

		//		motor[leftFront]= (j1y1+(j1x1/2))/slownessFactor;

		//	motor[rightFront]= (j1y1-(j1x1/2))/slownessFactor;

		//	motor[leftBack]= (j1y1+(j1x1/2))/slownessFactor;

		//	motor[rightBack]= (j1y1-(j1x1/2))/slownessFactor;

		//}

		//else{ //puts it into speed when the joystick passes a iuhgiugiguiug

		motor[leftFront]= (j1y1+(j1x1/2));

		motor[rightFront]= (j1y1-(j1x1/2));

		motor[leftBack]= (j1y1+(j1x1/2));

		motor[rightBack]= (j1y1-(j1x1/2));

		//}

	}

	else{

		motor[leftFront] = 0;

		motor[leftBack] = 0;

		motor[rightFront] = 0;

		motor[rightBack] = 0;

	}

}



void liftArm(){



	//}

	//controller 1 and two will be in control of the lift

	if(j1y2 > threshold || j1y2 < -threshold){

		motor[topPulley] = j1y2;

		motor[bottomPulley] = j1y2;

	}

	//else if(j1y2 > threshold || j1y2 < -threshold){

	//	motor[topPulley] = j1y2;

	//	motor[bottomPulley] = j1y2;

	//}

	else {

		motor[topPulley] = 0;

		motor[bottomPulley] = 0;

	}

}



void roller(bool scoopIn){

	if(scoopIn){

		motor[bucket] = 127;

	}

	else if(!scoopIn){

		motor[bucket] = -127;

	}

}



task main()

{

	initializeRobot();

	servo[guard] = 0;

	waitForStart();



	while (true){
		getJoystickValues();

		arcadeDrive();

		liftArm();






		if((joy1Btn(4) || joy2Btn(4))){

			motor[arm] = 25;

		}

		else if((joy1Btn(1) || joy2Btn(1))){

			motor[arm] = -20;

		}

		else{

			motor[arm] = 0;

		}

		//if(guardUp){

		//	servo[guard] = 250;

		//	guardUp  =false;

		//	wait1Msec(250);

		//}

		//else if(!guardUp){



		//	servo[guard] = 0;

		//	guardUp  =true;

		//	wait1Msec(250);

		// }



		if(joy2Btn(5) || joy1Btn(5)){

			servo[rightGrabber] = rightServoUp;

			servo[leftGrabber] = leftServoUp;

		}

		else if(joy2Btn(7) || joy1Btn(7)){

			servo[rightGrabber] = rightServoDown;

			servo[leftGrabber] = leftServoDown;

		}



		if(joy1Btn(6)){

			roller(true);

		}

		else if(joy1Btn(8)){

			roller(false);

		}

		else {

			motor[bucket] = 0;

		}

	}

}









//bool littleArmOnly = false;

//bool wholeArm = true;



//	if(joy1Btn(3)){ // little arm only

//		wholeArm = false;

//		littleArmOnly = true;

//	}

//else if(joy1Btn(2)){ // whole arm

//	littleArmOnly = false;

//	wholeArm = true;

//}

//else if(joy1Btn(1)){ // pulleys only

//	littleArmOnly = false;

//	wholeArm = false;

//}





//void tankDrive(){

//	//////Tank Drive//////Tank Drive//////Tank Drive//////Tank Drive//////Tank Drive

//  	if( j1y1 > 7 || j1y1 < -7){

//  		motor[leftFront]= (j1y1);

//  		motor[leftBack]= (j1y1);

//		}

//		else{

//			motor[leftFront]= 0;

//  		motor[leftBack]= 0;

//		}

//		if( j1y2 > 7 || j1y2 < -7){

//			motor[rightFront]= (j1y2);

//			motor[rightBack]= (j1y2);

//		}

//		else{

//			motor[rightFront]= 0;

//  		motor[rightBack]= 0;

//		}

////////End Of Tank Drive//////End Of Tank Drive//////End Of Tank Drive//////End Of Tank Drive

//}



//if(j1y2 < -3 || j1y2 > 3){

//	if(littleArmOnly){ // lift only rack-and-pinion

//		motor[arm] = j1y2;

//		nxtDisplayBigStringAt(0, 60, "LITTLE   ");

//	}

//	else if(wholeArm ){ //lift pulleys and rack-and-pinion

//		motor[arm] = j1y2;

//		motor[pulleyMotor] = j1y2;

//		nxtDisplayBigStringAt(0, 60, "WHOLE   ");

//	}

//	else if(!littleArmOnly && !wholeArm ){ //lift only pulleys

//		motor[pulleyMotor] = j1y2;

//		nxtDisplayBigStringAt(0, 60, "PULLEY   ");

//	}

// }

// else{

// 		motor[arm] = 0;

// 		motor[pulleyMotor] = 0;

// 	}
