#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     FrontLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     FrontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     BackLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     BackRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     Lift,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"
task main()
{
	waitForStart();
	while(true)
	{
		getJoystickSettings(joystick);
			if (joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10)
				{
						motor [FrontLeft] = 0;
						motor [BackLeft] = 0;
				}
			else
				{
					motor [FrontLeft] = joystick.joy1_y1;
					motor [BackLeft] = joystick.joy1_y1;
	 	  	}
			if (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)
				{
					motor [FrontRight] = 0;
					motor [BackRight] = 0;
				}
			else
				{
					motor [FrontRight] = joystick.joy1_y2;
					motor [BackRight] = joystick.joy1_y2;
				}
			if (joy1Btn(2) == 1 && joy1Btn(3) == 0)
			{
				motor[Lift] = 100;
			}
			else if (joy1Btn(3) == 1 && joy1Btn(2) == 0)
			{
				motor[Lift] = -100;
			}
			else
			{
				motor[Lift] = 0;
			}
	}
}
