#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"
task main()
{
	while(true)
	{
		getJoystickSettings(joystick);
		if (joystick.joy1_y1 > -10 && joystick.joy1_y1 < 10)
		{
			motor[left] = 0;
		}
		else
		{
			motor[left] = joystick.joy1_y1;
		}
		if (joystick.joy1_y2 > -10 && joystick.joy1_y2 < 10)
		{
			motor[right] = 0;
		}
		else
		{
			motor[right] = joystick.joy1_y2;
		}
		if (joystick.joy2_y1 > -10 && joystick.joy2_y1 < 10)
		{
			motor[lift] = 0;
		}
		else
		{
			motor[lift] = joystick.joy2_y1;
		}
			}
		}
