#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     br,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     tr,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     bl,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     tl,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     lifting,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    right,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    left,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//PURPOSE: 9110 TELE-OP
#include "joystickdriver.c"
task main()
{
	float claw = 127;

	while(true)
	{

		getJoystickSettings(joystick);

		if (joystick.joy1_y1 > -10 && joystick.joy1_y1 < 10)
		{
			motor[bl] = 0;
			motor[tl] = 0;
		}
		else
		{
			motor[bl] = ((joystick.joy1_y1)/3);
			motor[tl] = ((joystick.joy1_y1)/3);
		}

		if (joystick.joy1_y2 > -10 && joystick.joy1_y2 < 10)
		{
			motor[br] = 0;
			motor[tr] = 0;
		}
		else
		{
			motor[br] = ((joystick.joy1_y2)/3);
			motor[tr] = ((joystick.joy1_y2)/3);
		}

		if (joy2Btn(5) == 1 && joy2Btn(7) == 0)
		{
			motor[lifting] = 100;
		}
		else if(joy2Btn(5) == 0 && joy2Btn(7) == 1)
		{
			motor[lifting] = -100;
		}
		else
		{
			motor[lifting] = 0;
		}

		if(joy2Btn(8) == 1 && joy2Btn(6) == 0)
		{
			claw -= .2;
		}
		else if(joy2Btn(8) == 0 && joy2Btn(6) == 1)
		{
			claw += .2;
		}

		if(claw < 0)
		claw = 0;
		if(claw > 255)
		claw = 255;

		servo[left] = (int) claw;
		servo[right] = (int)(255-claw);
  }
}
