#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     lifting,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    claw,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    scooper,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,              tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"
float ser_claw;
float scoopt = 0;
task main()
{
ser_claw = 5;
while(true)
{
	getJoystickSettings(joystick);

	if(joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10)
	{
		motor[left] = 0;
	}
	else
	{
		motor[left] = joystick.joy1_y1;
	}
	if(joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)
	{
		motor[right] = 0;
	}
	else
	{
		motor[right] = joystick.joy1_y2;
	}
	if (joystick.joy2_y1 < 10 && joystick.joy2_y1 > -10)
	{
		motor[lifting] = 0;
	}
	else
	{
		motor[lifting] = joystick.joy2_y1;
	}


	if(joy1Btn(6) == 1 && joy1Btn(7) == 0)
	{
		ser_claw += 5;
	}
	else if(joy1Btn(7) == 1 && joy1Btn(6) == 0)
	{
		ser_claw -= 5;
	}



	if(joy2Btn(2) == 1 && scoopt == 0)
	{
		scoopt = 1;
		servo[scooper] = 0;
	}
	else if(joy2Btn(2) == 0 && scoopt == 1)
	{
		scoopt = 2;
	}
	else if(joy2Btn(2) == 1 && scoopt == 2)
	{
		scoopt = 3;
		servo[scooper] = 127;
	}
	else if(joy2Btn(2) == 0 && scoopt == 3)
	{
		scoopt = 0;
	}




	//Int Declaration
	if(ser_claw > 256)
		ser_claw = 256;
	else if(ser_claw < 0)
		ser_claw = 0;

	servo[claw] = (int) ser_claw;


}


}
