#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     sright,         sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     backleft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     frontleft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lifter,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     backright,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     frontright,    tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    conv,                 tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#define FORWARD_DIRECTION      1
#define BACKWARDS_DIRECTION   -1
#define STOP                   0

/* Function declaration */
float convv;
void runAllMotors( int speed );
void stopAllMotors();
void runConveyorBelt( byte direction );
void turnLeft( int delta );
void turnRight( int delta );

void initializeRobot()
{
	return;
}
task main()
{
	convv = 0;
	initializeRobot();
	waitForStart();

	/* Stage 1. Automation procedure to
	 * drop the block */

	// Run all motors at 50
	runAllMotors( 50 );
  wait1Msec(850);
  stopAllMotors();

  runConveyorBelt( FORWARD_DIRECTION );
  wait1Msec(1800);
  runConveyorBelt( BACKWARDS_DIRECTION );
  wait1Msec(1000);
  runConveyorBelt( STOP );

  // Moves robot back
  runAllMotors( -50 );
  wait1Msec(400);
  stopAllMotors();

  /* 2nd stage */
  turnRight( 50 );
  wait1Msec(400);

  runAllMotors( 50 );
  wait1Msec(600);
  stopAllMotors();

  turnLeft( 50 );
  wait1Msec(300);

  runAllMotors( 50 );
  wait1Msec(600);

  turnLeft( 50 );
  wait1Msec(300);

  runAllMotors( 50 );
  wait1Msec(600);

  turnLeft ( 50 );
  wait1Msec(900);

  runAllMotors( 50 );
  wait1Msec(850);
}
  /* End of Autonomous
   * Beginning of writing functions*/


  /*First function*/

void runAllMotors( int speed )
{
	/* Make sure that we don't overflow */
	if( speed > 127 )
		speed = 127;
  else if( speed < -127 )
  	speed = -127;

  /* Set motor speed */
	motor[backright] = speed;
  motor[frontright] = speed;
  motor[backleft] = speed;
  motor[frontleft] = speed;
}


  /*Second function*/

void stopAllMotors()
{
	runAllMotors(0); //set all motor power values to 0
}


  /*Third function*/

void runConveyorBelt( byte direction )
{
	if(direction == FORWARD_DIRECTION)
		servo[conv] = (int) 200; // pick any value from 128 to 255
	else if( direction == BACKWARDS_DIRECTION)
		servo[conv] = (int) 100; // pick any value from 0 to 127
  else if( direction == STOP)
    servo[conv] = (int) 127;
  else
  	servo[conv] = 127; //127 stops servo
}


  /*Fourth function*/

void turnLeft( int delta )
{
	motor[backleft] -= delta;
	motor[backright] += delta;
	motor[frontleft] -= delta;
	motor[frontright] += delta;
}


  /*Fifth function*/

void turnRight( int delta )
{
	motor[backleft] += delta;
	motor[backright] -= delta;
	motor[frontleft] += delta;
	motor[frontright] -= delta;
}
