#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     Gyro,     sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     omnibr,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     omnibl,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     omnitr,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     omnitl,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void runAllMotors(int speed);
void stopAllMotors(void);
void runAllRight( int speed );
void rotate(int speed);
int value = 0;
int degreesToTurn = 180;
float degreesSoFar = 0;
int initialTurnReading = SensorValue(Gyro);


void initializeRobot()
{
		return;
}
task main()
{
		runAllMotors(100);
		wait1Msec(1300);

}
void runAllMotors(int speed)
{
		if (speed > 127)
				speed = 127;
		else if( speed < -127)
				speed = -127;

		motor[omnitr] = speed;
		motor[omnibr] = -speed;
		motor[omnibl] = -speed;
		motor[omnitl] = speed;
}


void stopAllMotors()
{
		runAllMotors(0);
}

void runAllRight( int speed ) // Horizontal DIR
{
		motor[omnitr] = speed;
		motor[omnibr] = speed;
		motor[omnitl] = -speed;
		motor[omnibl] = -speed;

}

void rotate( int speed )
{
		motor[omnitr] = speed;
		motor[omnitl] = speed;
		motor[omnibr] = speed;
		motor[omnibl] = speed;
}
