#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     Gyro,     sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     omnibr,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     omnibl,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     omnitr,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     omnitl,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void runAllMotors(int speed);
void stopAllMotors(void);
void runAllRight( int speed );
void rotate(int speed);
int value = 0;
int degreesToTurn = 180;
float degreesSoFar = 0;
int initialTurnReading = SensorValue(Gyro);


void initializeRobot()
{
	return;
}
task main()
{

	initializeRobot();
	waitForStart();
  runAllMotors(-100);
  wait1Msec(1750);
  stopAllMotors();
  wait1Msec(100);
  rotate(-100);
  wait1Msec(600);
  if (SensorValue[IR] == 5 )
  {
  	value = 3;
  	rotate(100);
    wait1Msec(350);
  }
  else
  {
  rotate(100);
  wait1Msec(350);
  runAllMotors(100);
  while(SensorValue[IR] != 5 )
  {
  	wait1Msec(10);
  	value ++;
  }
  }
 	stopAllMotors();
 	wait1Msec(500);

 	if(value <= 40) //position 3
 	{

	rotate(100);
	wait1Msec(250);
  runAllMotors(-100);
  wait1Msec(1100);
  runAllRight(-100);
  wait1Msec(2550);
  runAllMotors(100);
	wait1Msec(1000);
	runAllRight(127);
	wait1Msec(2200);
 	}
 	else if( value > 20 && value <= 160) //position 2
	{
	runAllMotors(-100);
	wait1Msec(600);
	stopAllMotors();
	wait1Msec(300);
	runAllRight(-100);
	wait1Msec(610);
	stopAllMotors();
	wait1Msec(1000);
	runAllMotors(-100);
	wait1Msec(500);
	stopAllMotors();
	wait1Msec(1000);
  runAllRight(-100);
  wait1Msec(1400);
  runAllMotors(100);
  wait1Msec(670);
  runAllRight(127);
  wait1Msec(1650);
	}
	else if( value > 125 && value <= 200) //position 1
	{
	runAllMotors(100);
	wait1Msec(400);
	rotate(-100);
	wait1Msec(300);
	runAllMotors(100);
	wait1Msec(470);
	stopAllMotors();
	wait1Msec(1000);
	runAllRight(-100);
	wait1Msec(610);
	stopAllMotors();
	wait1Msec(1000);
	runAllMotors(-100);
	wait1Msec(700);
	stopAllMotors();
	wait1Msec(1000);
  runAllRight(-100);
  wait1Msec(1300);
  runAllMotors(100);
  wait1Msec(700);
  runAllRight(127);
  wait1Msec(1700);

}
} // End Task-Main

	/*rotate(100);
	wait1Msec(10000);
	stopAllMotors();
	wait1Msec(5000);

	if (value == 1)
	{
		rotate(100);
		wait1Msec(10000);
		stopAllMotors();
		wait1Msec(1000);
	}
	else if (value == 2)
	{
		rotate(-100);
		wait1Msec(10000);
		stopAllMotors();
		wait1Msec(1000);
	}


*/
// End task-main

void runAllMotors(int speed)
{
	if (speed > 127)
		speed = 127;
	else if( speed < -127)
		speed = -127;

		motor[omnitr] = speed;
		motor[omnibr] = -speed;
		motor[omnibl] = -speed;
		motor[omnitl] = speed;
}


void stopAllMotors()
{
	runAllMotors(0);
}

void runAllRight( int speed ) // Horizontal DIR
{
	motor[omnitr] = speed;
	motor[omnibr] = speed;
	motor[omnitl] = -speed;
	motor[omnibl] = -speed;

}

void rotate( int speed )
{
	motor[omnitr] = speed;
	motor[omnitl] = speed;
	motor[omnibr] = speed;
	motor[omnibl] = speed;
}
