#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     turnSensor,     sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     Sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     Backright,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Backleft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Frontright,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Frontleft,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"
void rotate ( int speed );
void runAllMotors ( int speed );
void runAllRight ( int speed );
float degreesSoFar = 0;
float initialTurnReading = SensorValue(turnSensor);
float nickfeet = 30;
int ref;

task main()
{
	waitForStart();

	runAllMotors(100);
	while(SensorValue[IR] != 3)
	{
		wait1Msec(10);
		ref++;
	}
	runAllMotors(0);
	wait1Msec(500);
	rotate(100);
	while (abs(degreesSoFar) < 35)
	{
		wait1Msec(10);
		int currentGyroReading3 = SensorValue(turnSensor) - initialTurnReading;
		degreesSoFar = degreesSoFar + currentGyroReading3*.01;
	}
	runAllMotors(0);
	wait1Msec(500);
	runAllMotors(100);
	while(SensorValue[Sonar] > (0.5*nickfeet))
	{
		wait1Msec(10);
	}
	runAllMotors(0);
	wait1Msec(500);
	runAllRight(100);
	wait1Msec(150);
	runAllMotors(0);
	wait1Msec(1000);
	runAllMotors(100);
	wait1Msec(1200);


}

void rotate ( int speed )
{
	motor[Frontleft] = speed;
	motor[Frontright] = speed;
	motor[Backleft] = speed;
	motor[Backright] = speed;
}
void runAllMotors( int speed )
{
	if (speed > 127)
		speed = 127;
	else if( speed < -127)
		speed = -127;

		motor[Frontright] = speed;
		motor[Backright] = -speed;
		motor[Backleft] = -speed;
		motor[Frontleft] = speed;
}
void runAllRight( int speed ) // Horizontal DIR
{
	motor[Frontright] = speed;
	motor[Backright] = speed;
	motor[Frontleft] = -speed;
	motor[Backleft] = -speed;
}
