#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Rightmotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Leftmotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     Lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{


while(true)
{
getJoystickSettings(joystick);

//wheel
	if(joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10)

	{
		motor[Leftmotor] = 0;
		motor[Rightmotor] = 0;

	}

	else if(joystick.joy1_y1 > 10)

	{
  motor[Leftmotor] = 70;
  motor[Rightmotor] = 70;

	}

	else if(joystick.joy1_y1 < -10)
	{
		motor[Leftmotor] = -70;
		motor[Rightmotor] = -70;
	}


	if(joystick.joy1_x2 < 10 && joystick.joy1_x2 > -10)
	{
	}

	else if( joystick.joy1_x2 > 10)
{
	motor[Leftmotor] = 70;
	motor[Rightmotor] = -70;
}

 else if(joystick.joy1_x2 < -10)
 {
   motor[Leftmotor] = -70;
   motor[Rightmotor] = 70;
 }


	//lift

		if	(joy1Btn(2) == 0)

	{
		motor[Lift] = 0;
	}

	else if (joy1Btn(2) == 1)

	{
		motor[Lift] = 100;
	}




}
}
