#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Backleft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Frontleft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Frontright,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Backright,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     Lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{


while(true)
{
getJoystickSettings(joystick);

//wheel
	if(joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10)

	{
		motor[Backleft] = 0;
		motor[Frontleft] = 0;

	}

	else

	{
		motor[Backleft] = joystick.joy1_y1;
		motor[Frontleft] = joystick.joy1_y1;

	}

			if	(joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)

	{
			motor[Backright] = 0;
		motor[Frontright] = 0;
	}

	else

	{
  	motor[Backright] = joystick.joy1_y1;
		motor[Frontright] = joystick.joy1_y1;
	}

	//Lift



  	if	(joy1Btn(2) == 0)

	{
		motor[Lift] = 0;
	}

	else if (joy1Btn(2) == 1)

	{
		motor[Lift] = 100;
	}




}
}
