#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     sright,         sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     backleft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     frontleft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lifter,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     backright,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     frontright,    tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    conv,                 tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
float convv;
float servo2v;
float servo3v;
void initializeRobot()
{
	return;
}
task main()
{
	convv = 0;
	servo2v = 0;
	servo3v = 0;
	initializeRobot();
	waitForStart();

	motor[backright] = 50;
  motor[frontright] = 50;
  motor[backleft] = 50;
  motor[frontleft] = 50;
  wait1Msec(400);
  convv += 20;
  servo[conv] = (int)convv;
  wait1Msec(500);
  motor[backright] = -50;
  motor[frontright] = -50;
  motor[backleft] = -50;
  motor[frontleft] = -50;
  wait1Msec(350);

  {
	while(true)
	{
		getJoystickSettings(joystick);

		//Wheels

		if (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10) //Right joystick moves back and front right wheels
		{
			motor[backright] = 0;
			motor[frontright] = 0;
		}
		else
	  {
	  	motor[backright] = joystick.joy1_y2;
	  	motor[frontright] = joystick.joy1_y2;
	  }
  	if (joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10) //Left joystick moves back and front left wheels
  	{
	  	motor[backleft] = 0;
	  	motor[frontleft] = 0;
  	}
  	else
  	{
  		motor[backleft] = joystick.joy1_y1;
  		motor[frontleft] = joystick.joy1_y1;
  	}

  	//Flag

  	if (joystick.joy2_y2 < 10 && joystick.joy2_y2 > -10)
  	{
  		motor[flag] = 0;
  	}
  	else
  	{
  		motor[flag] = joystick.joy2_y2;
  	}

  	//Lifting Mechanism

  	if (joystick.joy2_y1 < 10 && joystick.joy2_y1 > -10)
  	{
  		motor[lifter] = 0;
  	}
  	else
  	{
  		motor[lifter] = joystick.joy2_y1;
  	}

   	//Lockin Mechanism

  	if (joy2Btn(6) == 1 && joy2Btn(7) != 1)
  	{
  		servo2v += .1;
  	}
  	else if (joy2Btn(7) == 1 && joy2Btn(6) != 1)
  	{
  		servo3v -= .1;
  	}

  	if (servo2v < 0)
    servo2v = 0;
    else if(servo2v > 255)
    servo2v = 255;
    if (servo3v < 0)
    servo3v = 0;
    else if(servo3v > 255)
   	servo3v = 255;

   	servo[servo2] = 255 - (int) servo2;
    servo[servo3] = (int) servo3;

   }
}
}
