#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_2,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     conv,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     backright,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     frontright,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     frontleft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     backleft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     wheelturner,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
float rightv; //floats are decimals
float leftv;  //these variables controll the ser

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
void initializeRobot()
{
	  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
  return;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	rightv = 0;
	leftv = 0;
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  motor[backright] = 100;
  motor[frontright] = 100;
  motor[backleft] = 100;
  motor[frontleft] = 100;
wait1Msec(3500);
motor[backleft] = 100;
motor[frontleft] = 100;
motor[backright] = -100;
motor[frontright] = -100;
wait1Msec(2000);
motor[backright] = 100;
motor[frontright] = 100;
motor[backleft] = 100;
motor[frontleft] = 100;
wait1Msec(2000);
motor[conv] = 60;
wait1Msec(1000);
motor[backright] = 100;
motor[frontright] = 100;
motor[backleft] = -100;
motor[frontleft] = -100;
wait1Msec(2000);
motor[backright] = 100;
motor[frontright] = 100;
motor[backleft] = 100;
motor[frontleft] = 100;
wait1Msec(5500);
motor[backright] = -100;
motor[frontright] = -100;
motor[backleft] = 100;
motor[frontleft] = 100;
wait1Msec(2500);
motor[backright] = 100;
motor[frontright] = 100;
motor[backleft] = 100;
motor[frontleft] = 100;
wait1Msec(2000);
motor[backright] = -100;
motor[frontright] = -100;
motor[backleft] = 100;
motor[frontleft] = 100;
wait1Msec(5500);
motor[backright] = 100;
motor[frontright] = 100;
motor[backleft] = 100;
motor[frontleft] = 100;
wait1Msec(2500);

while (true)
{
		{
		getJoystickSettings(joystick);

		//Wheels

		if (joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10) //Right joystick moves back and front right wheels
		{
			motor[backright] = 0;
			motor[frontright] = 0;
		}
		else
	  {
	  	motor[backright] = joystick.joy1_y1;
	  	motor[frontright] = joystick.joy1_y1;
	  }
  	if (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10) //Left joystick moves back and front left wheels
  	{
	  	motor[backleft] = 0;
	  	motor[frontleft] = 0;
  	}
  	else
  	{
  		motor[backleft] = joystick.joy1_y2;
  		motor[frontleft] = joystick.joy1_y2;
  	}

  	//Conveyor Belt

  	if (joystick.joy2_y1 < 10 && joystick.joy2_y1 > -10) //Left joystick moves conveyor belt
  	{
  		motor[conv] = 0;
  	}
  	else
  	{
  		motor[conv] = joystick.joy2_y1;
  	}

  	//Wheel Turner

  	if (joystick.joy2_y2 < 10 && joystick.joy2_y2 > -10)
  	{
  		motor[wheelturner] = 0;
  	}
  	else // <-- this  means, execute statement if joy2Btn(4) == 0
  	{
  		motor[wheelturner] = joystick.joy2_y2;
  	}

}
}
}
