#pragma config(Hubs,  S1, HTMotor,  none,  none,  none)
#pragma config(Motor,  mtr_S1_C1_1,     Left,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Right,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"


task main()

{

while(true)

	{

getJoystickSettings(joystick);
	//Tells computor to check what state the joystick is.


	//Wheels* Tells computor to check joystick state and move motors acordingly.
		if(joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10)

		{
			motor[Left] = 0;
		}

	else

		{
			motor[Left] = joystick.joy1_y1;
		}


		if(joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)

		{
			motor[Right] = 0;
		}

	else

		{
			motor[Right] = joystick.joy1_y2;
		}


	}

}
