#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     Irseeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     right2,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     left2,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
     waitForStart();

    {
     if(SensorValue[Irseeker] != 5 )
{
	   motor[right] = 20;
     motor[right2]= 20;
     motor[left] =  20;
     motor[left2] = 20;
     wait1Msec(1000);
}
 else
{
  if(SensorValue[Irseeker] == 5)

   {
     motor[right] = 0;
     motor[right2]= 0;
     motor[left] =  0;
     motor[left2] = 0;
     //trigger block thingy
     wait1Msec(500);


     motor[right] = 100;
     motor[right2]= 100;
     motor[left] =  100;
     motor[left2] = 100;

     wait1Msec(500);






}}}}
