#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorNXT, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Joystickdriver.c"


task main()
{

while(true)
{

getJoystickSettings(joystick);

if (joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10)

	{
		motor[Left] = 0;
	}

	else

	{
		motor[Left] = joystick.joy1_y1;

	}

	if	(joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)

	{
		motor[Right] = 0;
}
	else

	{
		motor[Right] = joystick.joy1_y2;

	}
}
}
