#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     conv,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     backright,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     frontright,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     frontleft,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     backleft,      tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    LLS,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    LRS,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    RLS,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    RRS,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"
float LLSv;
float LRSv;
float RRSv;
float RLSv;

task main()
{
	LLSv = 0;
	LRSv = 0;
	RRSv = 0;
	RLSv = 0;
	while(true)
	{
		getJoystickSettings(joystick);

		//Wheels

		if (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10) //Right joystick moves back and front right wheels
		{
			motor[backright] = 0;
			motor[frontright] = 0;
		}
		else
	  {
	  	motor[backright] = joystick.joy1_y2;
	  	motor[frontright] = joystick.joy1_y2;
	  }
  	if (joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10) //Left joystick moves back and front left wheels
  	{
	  	motor[backleft] = 0;
	  	motor[frontleft] = 0;
  	}
  	else
  	{
  		motor[backleft] = joystick.joy1_y1;
  		motor[frontleft] = joystick.joy1_y1;
  	}

  	//Conveyor Belt

  	if (joystick.joy2_y1 < 10 && joystick.joy2_y1 > -10) //Left joystick moves conveyor belt
  	{
  		motor[conv] = 0;
  	}
  	else
  	{
  		motor[conv] = joystick.joy2_y1;
  	}

  	//Flag

  	if (joystick.joy2_y2 < 10 && joystick.joy2_y2 > -10) //Right joystick moves flag
  	{
  		motor[flag] = 0;
  	}
  	else
  	{
  		motor[flag] = joystick.joy2_y2;
  	}

  	//Flaps

  	if (joy2Btn(4) == 1 && joy2Btn(6) != 1)
  	{
  		LLSv += .1;
  	}
  	else if (joy2Btn(6) == 1 && joy2Btn(4) != 1)
  	{


  	if (joy2Btn(5) == 1 && joy2Btn(7) != 1)
  	{
  		LRSv += .1;
  	}
  	else if (joy2Btn(7) == 1 && joy2Btn(5) != 1)
  	{
  		LRSv -= .1;
  	}
  	if (joy2Btn(8) == 1 && joy2Btn(9) != 1)
  	{
  		RRSv += .1;
  	}
  	else if (joy2Btn(9) == 1 && joy2Btn(8) != 1)
  	{
  		RRSv -= .1;
  	}
  	if (joy2Btn(10) == 1 && joy2Btn(11) != 1)
  	{
  		RLSv += .1;
  	}
  	else if (joy2Btn(11) == 1 && joy2Btn(10) != 1)
  	{
  		RLSv -= .1;
  	}
  	if (LLSv < 0)
  	  LLSv = 0;
    else if(LLSv > 255)
      LLSv = 255;
    if (LRSv < 0)
    	LRSv = 0;
    else if(LRSv > 255)
    	LRSv = 255;
    if (RRSv < 0)
    	RRSv = 0;
    else if(RRSv > 255)
    	RRSv = 255;
    if (RLSv < 0)
    	RLSv = 0;
    else if(RLSv > 255)
    	RLSv = 255;

    	servo[LLS] = 255 - (int) LLSv;
    	servo[LRS] = (int) LRSv;
    	servo[RRS] = 255 - (int) RRSv;
    	servo[RLS] = (int) RLSv;


}
}
