#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     conv,        tmotorTetrix, openLoop)
#pragma config(Motor, mtr_S1_C1_2,      flag,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     backright,    tmotorMatrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     frontright,     tmotorMatrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     frontleft,     tmotorMatrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     backleft,     tmotorMatrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    right,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    left,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c" // Tells ROBOTC to include the driver file for the joysti ck.
float rightv; //floats are decimals
float leftv;  //these variables controll the servos
task main()   //the decimals gives us more precise controll
{
	rightv = 0;
	leftv = 0;
while (true)
  {
  	//wheels
    getJoystickSettings(joystick); // Updates Buttons and Joysticks

    if (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)  /* Makes left side wheels move in tandem and same speed */
    {																											// Makes motors = joystick move
    																											//	but if at 10 or negative 10 stop
      motor[backright] = 0;  // just states if joystick = 10 or -10 motor = 0
      motor[frontright] = 0;

    }
    else
    {
    	motor[backright] = joystick.joy1_y2;
			motor[frontright] = joystick.joy1_y2; // if it is above 10 or -10 then the motor power = the joystick.
    }

    if (joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10)  /* Makes left side wheels move in tandem and same speed */
    {																											// Makes motors = joystick move
    																											//	but if at 10 or negative 10 stop
      motor[backleft] = 0; // joystick if 10 or -10 = motor power = 0
      motor[frontleft] = 0;

    }
    else
    {
      motor[backleft] = joystick.joy1_y1;  // if it is above 10 or -10 then the motor power = the joystick.
      motor[frontleft] = joystick.joy1_y1;

    }
    //conveyor belt
      if (joystick.joy2_y1 < 10 && joystick.joy2_y1 > -10)
    {
      motor[conv] = 0;
    }
    else
    {
      motor[conv] = joystick.joy2_y1;
    }
    //flaps
    if (joy2Btn(4) == 1 && joy2Btn(6) != 1)// incase some baka hits up and down on one servo at the same time
    {
      leftv += .1;                      // note to self add button numbers and check the rotation speed
    }
    else if (joy2Btn(6) == 1 && joy2Btn(4) != 1)
    {
      leftv -= .1;
    }
    if (joy2Btn(5) == 1 && joy2Btn(7) != 1)
    {
     	rightv += .1;
    }
    else if (joy2Btn(7) == 1 && joy2Btn(5) != 1)
    {
  	  rightv -= .1;
    }

    if(rightv < 0)  //note to self check range
    		rightv = 0;
      else if(rightv > 255)
      	rightv = 255;
      if(leftv < 0)
    		leftv = 0;
      else if(leftv > 255)
      	leftv = 255;

      	servo[right] = 255 - (int) rightv; // note to self check reversal
      	servo[left] = (int) leftv;

      	//flag
    if (joystick.joy2_y2 < 10 && joystick.joy2_y2 > -10)
    {
      motor[flag] = 0;
    }
    else
    {
      motor[flag] = joystick.joy2_y2;
    }

    }
}
