#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     turnSensor,     sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     Frontleft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Frontright,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Backleft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Backright,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void rotate ( int speed );

#include "joystickdriver.c"
task main()
{
	waitForStart();
	// take initial reading from gyro
	int degreesToTurn = 360;
	float degreesSoFar = 0;
	int initialTurnReading = SensorValue(turnSensor);

	// start turning
	rotate(50*sgn(degreesToTurn));

	// check if we have turned enough
	while(abs(degreesSoFar) < 360)
	{
		// update degreesSoFar
		wait1Msec(10);
		int currentGyroReading = SensorValue(turnSensor) - initialTurnReading;
		degreesSoFar = degreesSoFar + currentGyroReading*.01;
	}

	// stop turning
	rotate ( 0 );

}

void rotate ( int speed )
{
	motor[Frontleft] = speed;
	motor[Frontright] = speed;
	motor[Backleft] = speed;
	motor[Backright] = speed;
}
