#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     sright,         sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     backleft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     frontleft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lifter,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     back,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     front,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    sifter,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"
float pullup_lock;

task main()
{
	int x = 1;
	pullup_lock = 0;
	while(true)
	{
		getJoystickSettings(joystick);

		//	Wheels
    if (joy1Btn(8) == 1)
    {
      x = 4;     //we divided the joystick value by x to controll the speed when rasing the flag
    }
    else
    {
      x = 1;
    }
		if (joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10) //Right joystick moves back and front right wheels
		{
			motor[back] = 0;
			motor[front] = 0;
		}
		else
	  {
	  	motor[back] = (joystick.joy1_y1)/x;
	  	motor[front] = (joystick.joy1_y1)/x;
	  }
  	if (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10) //Left joystick moves back and front left wheels
  	{
	  	motor[backleft] = 0;
	  	motor[frontleft] = 0;
  	}
  	else
  	{
  		motor[backleft] = (joystick.joy1_y2)/x;
  		motor[frontleft] = (joystick.joy1_y2)/x;
  	}
  }}
