#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     omnibr,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     omnibl,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     omnitr,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     omnitl,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void runAllMotors(int speed);
void stopAllMotors(void);
void runAllRight( int speed );
void rotate(int speed);
void die(int speed);
int value = 1;

void initializeRobot()
{
	return;
}
task main()
{

	initializeRobot();
	waitForStart();
  runAllMotors(-100);
  wait1Msec(2100);
  rotate(-100);
  wait1Msec(350);
  runAllMotors(100);
  wait1Msec(1000);
  stopAllMotors();
  wait1Msec(1000);
  for (int b = 1; b < 4; b++)
  {
  	if (SensorValue[IR] == 5)
  	{
  		value = b;
  		break;
  	}
  	else
  	{
  		if (b == 1)
  		{
  			runAllMotors(100);
  			wait1Msec(800);
  		}
  		if (b == 2)
  		{
  			runAllMotors(100);
  			wait1Msec(600);
  		}
  		if (b == 3)
  		{
  			runAllMotors(100);
  			wait1Msec(600);
  		}
  		if (b == 4 && value == 0)
  		{
  			value = 4;
  		}
  	} // Close Else
  } // Close For


	    if( value !=  0)
			{

	stopAllMotors();
	wait1Msec(2000);

	if (value == 1)
	{
		runAllMotors(-100);
		wait1Msec(300);
		die(-100);
		wait1Msec(1200);
		stopAllMotors();
		wait1Msec(1500);
	}
	if (value == 2)
	{
		rotate(-100);
		wait1Msec(10000);
		stopAllMotors();
		wait1Msec(1000);
	}
	if (value == 3)
	{
		rotate(100);
		wait1Msec(10000);
		stopAllMotors();
		wait1Msec(1000);
	}
	if (value == 4)
	{
		rotate(-100);
		wait1Msec(10000);
		stopAllMotors();
		wait1Msec(1000);
	}


}
 stopAllMotors();
} // End task-main


void runAllMotors(int speed)
{
	if (speed > 127)
		speed = 127;
	else if( speed < -127)
		speed = -127;

		motor[omnitr] = speed;
		motor[omnibr] = -speed;
		motor[omnibl] = -speed;
		motor[omnitl] = speed;
}


void stopAllMotors()
{
	runAllMotors(0);
}

void runAllRight( int speed )
{
	motor[omnitr] = speed;
	motor[omnibr] = -speed;
	motor[omnitl] = speed;
	motor[omnibl] = -speed;

}

void rotate( int speed )
{
	motor[omnitr] = speed;
	motor[omnitl] = speed;
	motor[omnibr] = speed;
	motor[omnibl] = speed;
}

void die ( int speed ) // HORIZAONTAL MOVEMENT ON POSITIVE X DIR
{
	motor[omnitr] = speed;
	motor[omnitl] = -speed;
	motor[omnibr] = speed;
	motor[omnibl] = -speed;
}
