#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     left2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     right2,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     leftarm,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     claw,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    flaglift,      tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_2,    leftservo,     tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    rightservo,    tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,        tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,        tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,        tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Setting up variables
#include "JoystickDriver.c"
 float wrist_angle;
 float arm_lift;
 float flag_lift;
 float claw_speed;



task main()
{
	/* Init */
	wrist_angle = 0;
  arm_lift = 0;
  claw_speed = 0;
  flag_lift = 0;

while (true)
  {
  	//wheels
    getJoystickSettings(joystick);

    if (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)  /* Makes left side wheels move in tandem and same speed */
    {																											// Makes motors = joystick move																										//	but if at 10 or negative 10 stop
      motor[right] = 0;																		// just states if joystick = 10 or -10 motor = 0
      motor[right2] = 0;

    }
    else
    {
      motor[right] = joystick.joy1_y2;
			motor[right2] = joystick.joy1_y2; // if it is above 10 or -10 then the motor power = the joystick.
    }

    if (joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10)  /* Makes left side wheels move in tandem and same speed */
    {																											// Makes motors = joystick move
      motor[left] = 0;																		// but if at 10 or negative 10 stop
      motor[left2] = 0;
    }
    else
    {
      motor[left] = joystick.joy1_y1;  // if it is above 10 or -10 then the motor power = the joystick.
      motor[left2] = joystick.joy1_y1;
    }

    //Arm Y axis
    	if (joystick.joy2_y1 < 10 && joystick.joy2_y1 > -10)
  	{
  		motor[leftarm] = 0;
  	}
		else
		{
			motor[leftarm] = joystick.joy2_y1;
		}


    //Wrist
    	if (joystick.joy2_y2 > 10)
    	{
    			wrist_angle += .1;
    	}
    	else if (joystick.joy2_y2 < -10)
    	{
    			wrist_angle -= .1;
    	}
    //Claw motor
    	if ( joy2Btn(6) == 1 && joy2Btn(7) == 0 )
    	{
    		motor[claw] = 100;
    	}
    	else if ( joy2Btn(7) == 1 && joy2Btn(6) == 0)
    	{
    		motor[claw] = -100;
    	}

	//check range
	if(wrist_angle < 0)
    		wrist_angle = 0;
      else if(wrist_angle > 255)
      	wrist_angle = 255;
  if(arm_lift < 0)
    		arm_lift = 0;
      else if(arm_lift > 255)
      	arm_lift = 255;
  if(flag_lift < 0)
  			flag_lift = 0;
			else if(flag_lift > 255)
				flag_lift = 255;



		servo[leftservo] = 255 - (int) wrist_angle;
    servo[rightservo] = (int) wrist_angle;
    servo[flaglift] = (int) flag_lift;

    // I THEORY THIS SHOULD ALL WORK.... BUT THEN AGAIN IT IS JUST PROGRAME THEORY
}
}
