#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     right2,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     left2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     arm,           tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    wrist3,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    wrist2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    wrist,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "JoystickDriver.c"

 float wrist_angle;
 float merp_servo;

task main()
{
	/* Init */
	wrist_angle = 0;
  merp_servo = 0;


while (true)
  {
  	//wheels
    getJoystickSettings(joystick);





    if (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)  /* Makes left side wheels move in tandem and same speed */
    {																											// Makes motors = joystick move
    																											//	but if at 10 or negative 10 stop
      motor[right] = 0;
      motor[right2] = 0;  // just states if joystick = 10 or -10 motor = 0

    }
    else
    {
      motor[right] = joystick.joy1_y2;
			motor[right2] = joystick.joy1_y2; // if it is above 10 or -10 then the motor power = the joystick.
    }






    if (joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10)  /* Makes left side wheels move in tandem and same speed */
    {																											// Makes motors = joystick move
    																											//	but if at 10 or negative 10 stop
      motor[left] = 0;
      motor[left2] = 0; // joystick if 10 or -10 = motor power = 0

    }
    else
    {
      motor[left] = joystick.joy1_y1;  // if it is above 10 or -10 then the motor power = the joystick.
      motor[left2] = joystick.joy1_y1;

    }




    //Arm
    /*
       if (joystick.joy2_y2 < 10 && joystick.joy2_y2 > -10)
    {
      motor[arm] = 0;


    }
    else
    {
      motor[arm] = joystick.joy2_y2;


    }
    */

    if(Joy1Btn(1) == 1 && Joy1Btn(2) == 0)
    {
    	motor[arm] = 100;
    }
    else if(Joy1Btn(2) == 1 && Joy1Btn(1) == 0)
    {
    	motor[arm] = -100;
    }
    else
    {
    	motor[arm] = 0;
    }



    //Wrist
    	if (joystick.joy2_y1 > 10)
    	{
    			wrist_angle += .1;
    	}
    	else if (joystick.joy2_y1 < -10)
    	{
    			wrist_angle -= .1;
    	}

    	// pouch
    	if(joy2Btn(2) == 1 && joy2Btn(3) == 0)
    	{
    			merp_servo = 255;
      }
    	else if(joy2Btn(3) == 1 && joy2Btn(2) == 0)
    	{
    			merp_servo = 0;
    	}

    	/*Check range. The servo range will be 0 to 255 (8 bit resolution) */
    	if(wrist_angle < 0)
    		wrist_angle = 0;
      else if(wrist_angle > 255)
      	wrist_angle = 255;
      if(merp_servo < 0)
    		merp_servo = 0;
      else if(merp_servo > 255)
      	merp_servo = 255;

      servo[wrist3] = (int) merp_servo;

      /* These 2 servos are opposite to each other. One rotates clockwisem
       * while the other rotates counter-clockwise. Be mindful of this otherwise
       * you'll burn the weaker servo... Angel */
      servo[wrist] = 255 - (int) wrist_angle;
      servo[wrist2] = (int) wrist_angle;
	}
}
