#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     omnitr,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     omnitl,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     omnibr,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     omnibl,        tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"
task main()
{
while(true)
{
	if (joystick.joy1_y1 > -5 && joystick.joy1_y1 < 5)
	{
		motor[omnitl] = 0;
	  motor[omnibl] = 0;
	}
	else
	{
		motor[omnitl] = joystick.joy1_y1;
		motor[omnibl] = joystick.joy1_y1;
	}
	if (joystick.joy1_y2 > -5 && joystick.joy1_y2 < 5)
	{
		motor[omnitr] = 0;
		motor[omnibr] = 0;
	}
	else
	{
		motor[omnitr] = joystick.joy1_y2;
		motor[omnibr] = joystick.joy1_y2;
	}




}


}
