#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     right2,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     left2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     leftarm,       tmotorTetrix, openloop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     rightarm,      tmotorTetrix, openloop)
#pragma config(Motor,  mtr_S1_C4_1,     claw,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     slide,           tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_2,    wrist3,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    wrist2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    wrist,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
 float wrist_angle;
 float merp_servo;

task main()
{
	/* Init */
	wrist_angle = 0;
  merp_servo = 0;

  while (true)
  {
  	//wheels
    getJoystickSettings(joystick);

    if (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)  /* Makes left side wheels move in tandem and same speed */
    {																											// Makes motors = joystick move
    																											//	but if at 10 or negative 10 stop
      motor[right] = 0;
      motor[right2] = 0;  // just states if joystick = 10 or -10 motor = 0

    }
    else
    {
      motor[right] = joystick.joy1_y2;
			motor[right2] = joystick.joy1_y2; // if it is above 10 or -10 then the motor power = the joystick.
    }

    if (joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10)  /* Makes left side wheels move in tandem and same speed */
    {																											// Makes motors = joystick move
    																											//	but if at 10 or negative 10 stop
      motor[left] = 0;
      motor[left2] = 0; // joystick if 10 or -10 = motor power = 0

    }
    else
    {
      motor[left] = joystick.joy1_y1;  // if it is above 10 or -10 then the motor power = the joystick.
      motor[left2] = joystick.joy1_y1;

    }

    //Arm
       if (joystick.joy2_y2 < 10 && joystick.joy2_y2 > -10)
    {
      motor[slide] = 0;


    }
    else
    {
      motor[slide] = joystick.joy2_y2;


    }
		 if (joystick.joy2_y1 < 10 && joystick.joy2_y1 > -10)
	{
