#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     FrontRight,    				tmotorNXT, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     BackRight,     				tmotorNXT, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     FrontLeft,     				tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     BackLeft,      				tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     PullUp,        				tmotorNXT, openLoop)
#pragma config(Servo,  srvo_S1_C4_2,    armlift,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_1,    flagturner,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_3,    servoright,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servoleft,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
float arm_lift;
float flag_lift;
float wrist_angle;
float flag_turner;


task main()
{
//Int//
arm_lift = 0;
flag_lift = 0;
wrist_angle = 0;


while(true)

	{

getJoystickSettings(joystick);


//wheels

	if(joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10)

	{
		motor[FrontLeft] = 0;
		motor[BackLeft] = 0;
	}

	else

	{
		motor[FrontLeft] = joystick.joy1_y1;
		motor[BackLeft] = joystick.joy1_y1;
	}

	if	(joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)

	{
		motor[FrontRight] = 0;
		motor[BackRight] = 0;
	}

	else

	{
		motor[FrontRight] = joystick.joy1_y2;
		motor[BackRight] = joystick.joy1_y2;
	}


	//Pull Up


	if (	joy2Btn(4) == 1 && joy2Btn(5) == 0)

	{
		motor[PullUp] = -100;
	}

	else if (	joy2Btn(4) == 0 && joy2Btn(5) == 0)

	{
		motor[PullUp] = 0;
	}

	else if ( joy2Btn(4) == 0 && joy2Btn(5) == 1)

	{
		motor[PullUp] = 100;
	}

	else if ( joy2Btn(4) == 0 && joy2Btn(5) == 0)

	{
		motor[PullUp] = 0;
	}


	//Arm Lift


	if ( joy1Btn(4) == 1 && joy1Btn(5) == 0)

	{
		arm_lift -= .7;
	}

	else if (	joy1Btn(4) == 0 && joy1Btn(5) == 0)

	{
		arm_lift = 0;
	}

	else if ( joy1Btn(4) == 0 && joy1Btn(5) == 1)

	{
		arm_lift += .7;
	}

	else if ( joy1Btn(4) == 0 && joy1Btn(5) == 0)

	{
		arm_lift = 0;
	}


	//Flag Lift


  if	(joy2Btn (6) == 0 && joy2Btn (7) == 1)

	{
  	flag_lift = 255;
  }

  else if (joy2Btn (6) == 0 && joy2Btn (7) == 0)

	{
  	flag_lift = 0;
  }

  else if (joy2Btn (6) == 1 && joy2Btn (7) == 0)

	{
  	flag_lift = -255;
  }

  else if (joy2Btn (6) == 0 && joy2Btn (7) == 0)

	{
  	flag_lift = 0;
  }


  //wrist angle


  if (joy1Btn (1) == 0 && joy2Btn (3) == 1)

	{
		wrist_angle += .9;
	}

	else if (joy2Btn (1) == 1 && joy2Btn (3) == 0)

	{
		wrist_angle -= .9;
	}


	//Setting up range of Servos//


	if(arm_lift < 0)
    		 arm_lift = 0;
      else if(arm_lift > 255)
      	arm_lift = 255;
	if(flag_lift < 0)
    		 flag_lift = 0;
      else if(flag_lift > 255)
      	flag_lift = 255;
	if(wrist_angle < 0)
    		 wrist_angle = 0;
      else if(wrist_angle > 255)
      	wrist_angle = 255;


  //Int servos//

	servo[armlift] = (int) arm_lift;
	servo[servoright] = (int) wrist_angle;
	servo[servoleft] = 255 - (int) wrist_angle;
	servo[flagturner] = (int) flag_turner;

}
}
