#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     RightMotor,    tmotorMatrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     LeftMotor,     tmotorMatrix, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c" // Tells ROBOTC to include the driver file for the joystick.
task main()
{
while (true)
  {
  	//wheels
    getJoystickSettings(joystick); // Update Buttons and Joysticks

    if (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)  /* Makes left side wheels move in tandem and same speed */
    {																											// Makes motors = joystick move
    																											//	but if at 10 or negative 10 stop
      motor[RightMotor] = 0;  // just states if joystick = 10 or -10 motor = 0

    }
    else
    {
			motor[RightMotor] = joystick.joy1_y2; // if it is above 10 or -10 then the motor power = the joystick.
    }

    if (joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10)  /* Makes left side wheels move in tandem and same speed */
    {																											// Makes motors = joystick move
    																											//	but if at 10 or negative 10 stop
      motor[LeftMotor] = 0; // joystick if 10 or -10 = motor power = 0

    }
    else
    {
      motor[LeftMotor] = joystick.joy1_y1;  // if it is above 10 or -10 then the motor power = the joystick.

    }


}
}
