#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     RightENC,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     Rightlift,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     intake,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     LeftENC,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     Left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     Leftlift,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_2,    winch,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    blrg,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    draw,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// PURPOSE: OFFICIAL AUTONOMOUS FOR STATES ROBOT.
#include "joystickdriver.c"

task main()
{
	int intk = 0;
	int winchv = 0;
	int blrgt = 0;
	int drawv = 0;
	servo[draw] =  22;
while(true)
{

getJoystickSettings(joystick);

if(joystick.joy1_y1 > -10 && joystick.joy1_y1 < 10)
{
	motor[Left] = 0;
	motor[LeftENC] = 0;

}
else
{
	motor[LeftENC] = joystick.joy1_y1;
	motor[Left] = joystick.joy1_y1;
	}

if(joystick.joy1_y2 > -10 && joystick.joy1_y2 < 10)
{
  motor[Right] = 0;
	motor[RightENC] = 0;

}
else
{
	motor[Right] = joystick.joy1_y2;
	motor[RightENC] = joystick.joy1_y2;

}


if( joy1Btn(2) == 1 && intk == 0)
{
	intk = 1;
	motor[intake] = -100;
}
else if(joy1Btn(2) == 0 && intk == 1)
{
	intk = 2;
}
else if(joy1Btn(2) == 1 && intk == 2)
{
	intk = 3;
	motor[intake] = 0;
}
else if(joy1Btn(2) == 0 && intk == 3)
{
	intk = 0;
}

if(servo[draw] > 21)
{
	motor[intake] = 0;
	intk = 0;
}


if(joy1Btn(5) == 1 && joy1Btn(7) == 0)
{
	motor[Leftlift] = 100;
	motor[Rightlift] = 100;
}
else if(joy1Btn(5) == 0 && joy1Btn(7) == 1)
{
	motor[Leftlift] = -100;
	motor[Rightlift] = -100;
}
else
{
	motor[Leftlift] = 0;
	motor[Rightlift] = 0;

}



if( joy1Btn(3) == 1 && winchv == 0)
{
	winchv = 1;
	servo[winch] = 38;
}
else if(joy1Btn(3) == 0 && winchv == 1)
{
	winchv = 2;
}
else if(joy1Btn(3) == 1 && winchv == 2)
{
	winchv = 3;
	servo[winch] = 48;
}
else if(joy1Btn(3) == 0 && winchv == 3)
{
	winchv = 0;
}


if( joystick.joy1_TopHat == 3 && blrgt == 0)
{
	blrgt = 1;
	servo[blrg] = 100;
}
else if(joystick.joy1_TopHat != 3 && blrgt == 1)
{
	blrgt = 2;
}
else if(joystick.joy1_TopHat == 3 && blrgt == 2)
{
	blrgt = 3;
	servo[blrg] = 255;
}
else if(joystick.joy1_TopHat != 3 && blrgt == 3)
{
	blrgt = 0;
}


if( joystick.joy1_TopHat == 4 && drawv == 0)
{
	drawv = 1;
	servo[draw] = 22;
}
else if(joystick.joy1_TopHat != 4 && drawv == 1)
{
	drawv = 2;
}
else if(joystick.joy1_TopHat == 4 && drawv == 2)
{
	drawv = 3;
	servo[draw] = 15;
}
else if(joystick.joy1_TopHat != 4 && drawv == 3)
{
	drawv = 4;
}
else if(joystick.joy1_TopHat == 4 && drawv == 4)
{
	drawv = 5;
	servo[draw] = 9;
}
else if(joystick.joy1_TopHat != 4 && drawv == 5)
{
	drawv = 6;
}
else if(joystick.joy1_TopHat == 4 && drawv == 6)
{
	drawv = 7;
	servo[draw] = 15;
}
else if(joystick.joy1_TopHat != 4 && drawv == 7)
{
	drawv = 0;
}





}



}
