#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     omnibr,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     omnitr,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     omnitl,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     omnibl,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     line1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     line2,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    base_r,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    base_l,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Code for the coolest robot of all time while logged in as root
#include "joystickdriver.c"

bool tank;
float base_servos;

task main()
{
	base_servos = 0;
	tank = false;
  while (true)
{

	getJoystickSettings(joystick);

	if (base_servos < 50) // Omni-wheel Drive
    {
			if (joystick.joy1_x2 < 10 && joystick.joy1_x2 > -10 && joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10 && joystick.joy1_x1 < 10 && joystick.joy1_x1 > -10 && joy1Btn(06) == 0 && joy1Btn(05)== 0 && joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)
				{
				  motor[omnitl] = 0;
			    motor[omnibl] = 0;
			    motor[omnitr] = 0;
			    motor[omnibr] = 0;
			  }

			// Joy1_y1
			if (joystick.joy1_y1 > 10)
			{
				motor[omnitl] = -joystick.joy1_y1;
			  motor[omnibl] = -joystick.joy1_y1;
			  motor[omnitr] = joystick.joy1_y1;
			  motor[omnibr] = joystick.joy1_y1;
			}
			else if(joystick.joy1_y1 < -10)
			{
				motor[omnitl] = -joystick.joy1_y1;
				motor[omnibl] = -joystick.joy1_y1;
				motor[omnitr] = joystick.joy1_y1;
				motor[omnibr] = joystick.joy1_y1;
			}

			// Joy1_x1
			else if (joystick.joy1_x1 > 10)
			{
				motor[omnitr] = -joystick.joy1_x1;
				motor[omnibr] = joystick.joy1_x1;
				motor[omnitl] = -joystick.joy1_x1;
				motor[omnibl] = joystick.joy1_x1;
			}
			else if (joystick.joy1_x1 < -10)
			{
				motor[omnitr] = -joystick.joy1_x1;
				motor[omnibr] = joystick.joy1_x1;
				motor[omnitl] = -joystick.joy1_x1;
				motor[omnibl] = joystick.joy1_x1;
			}

			// Buttons 5 and 6 False
			if(joy1Btn(05) == 1 && joy1Btn(06) == 0)
			{
				motor[omnitr] = 127;
				motor[omnibr] = 127;
				motor[omnitl] = 127;
				motor[omnibl] = 127;
			}

			// Buttons 5 and 6 True
			if(joy1Btn(05) == 0 && joy1Btn(06) == 1)
			{
				motor[omnitr] = -127;
				motor[omnibr] = -127;
				motor[omnitl] = -127;
				motor[omnibl] = -127;
			}

			// Joy1_y2
		  if (joystick.joy1_y2 > 10)
		  {
		  	motor[omnitl] = -joystick.joy1_y2;
		  	motor[omnibr] = joystick.joy1_y2;
		  }
		  else if (joystick.joy1_y2 < -10)
		  {
		  	motor[omnitl] = -joystick.joy1_y2;
		  	motor[omnibr] = joystick.joy1_y2;
		  }

		  // Joy1_x2
			else if (joystick.joy1_x2 > 10)
			{
				motor[omnibl] = -joystick.joy1_x2;
				motor[omnitr] = joystick.joy1_x2; //if you can find this good for you - S3b4ss
			}
			else if (joystick.joy1_x2 < -10)
			{
				motor[omnibl] = -joystick.joy1_x2;
				motor[omnitr] = joystick.joy1_x2;
			}

	} // if base_servos < 50 close

			else
			{ // Tank drive when base_servos > 50

	      if (joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10)
				{
					motor[omnitr] = 0;
					motor[omnibr] = 0;
				}
				else
				{
					motor[omnitr] = -joystick.joy1_y1;
					motor[omnibr] = -joystick.joy1_y1;
				}
				if (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)
				{
					motor[omnitl] = 0;
					motor[omnibl] = 0;
				}
				else
				{
					motor[omnitl] = joystick.joy1_y2;
					motor[omnibl] = joystick.joy1_y2;
				}

	} // close else statement when base_servos > 50

			// Button 4 True and Button 3 False
	  	if (joy1Btn(04) == 1 && joy1Btn(03) == 0)
			{
				base_servos += 5;
			}
			// Button 3 True and Button 4 False
			else if (joy1Btn(03) == 1 && joy1Btn(04) == 0)
			{
				base_servos -= 5;
			}
			// Button 1 True and Button 2 False
			else if (joy1Btn(01) == 1 && joy1Btn(02) == 0)
			{
				motor[line1] = 100;
			}
			// Button 2 True and Button 1 False
			else if (joy1Btn(02) == 1 && joy1Btn(01) == 0)
			{
				motor[line2] = 100;
			}

			// Check range base_servos
			if (base_servos < 0)
			base_servos = 0;
			else if(base_servos > 256)
			base_servos = 256;

			// Int declaration
			servo[base_l] = (int) base_servos;
			servo[base_r] = (int) base_servos;

		} // Close while (true) loop

} // Close task main()
