#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     arm_scoop,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     omnitr,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     omnibr,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     raising,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     omnitl,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     omnibl,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_1,     trunk,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    dtbr,                 tServoStandard)//#pragma config(Servo,  srvo_S1_C2_2,    rg1,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_1,    dtbl,                 tServoStandard)//#pragma config(Servo,  srvo_S2_C1_2,    rg2,                  tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//PURPOSE: OFFICIAL TELE-OP PROGRAM FOR 'BAE' ROBOT
//Code for the coolest robot of all time while logged in as root
#include "joystickdriver.c"

bool tank;
float base_servos;
float d;
float s;
float rg_right;
float rg_left;
task main()
{
	d = 0;
	s = 0;
	rg_right = 0;
	rg_left = 0;
	base_servos = 0;
	tank = false;
  while (true)
{

	getJoystickSettings(joystick);

	if (base_servos < 50) // Omni-wheel Drive
    {
			if (joystick.joy1_x2 < 10 && joystick.joy1_x2 > -10 && joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10 && joystick.joy1_x1 < 10 && joystick.joy1_x1 > -10 && joy1Btn(06) == 0 && joy1Btn(05)== 0 && joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)
				{
				  motor[omnitl] = 0;
			    motor[omnibl] = 0;
			    motor[omnitr] = 0;
			    motor[omnibr] = 0;
			  }

			// Joy1_y1
			if (joystick.joy1_y1 > 10)
			{
				motor[omnitl] = -joystick.joy1_y1;
			  motor[omnibl] = -joystick.joy1_y1;
			  motor[omnitr] = joystick.joy1_y1;
			  motor[omnibr] = joystick.joy1_y1;
			}
			else if(joystick.joy1_y1 < -10)
			{
				motor[omnitl] = -joystick.joy1_y1;
				motor[omnibl] = -joystick.joy1_y1;
				motor[omnitr] = joystick.joy1_y1;
				motor[omnibr] = joystick.joy1_y1;
			}

			// Joy1_x1
			else if (joystick.joy1_x1 > 10)
			{
				motor[omnitr] = -joystick.joy1_x1;
				motor[omnibr] = joystick.joy1_x1;
				motor[omnitl] = -joystick.joy1_x1;
				motor[omnibl] = joystick.joy1_x1;
			}
			else if (joystick.joy1_x1 < -10)
			{
				motor[omnitr] = -joystick.joy1_x1;
				motor[omnibr] = joystick.joy1_x1;
				motor[omnitl] = -joystick.joy1_x1;
				motor[omnibl] = joystick.joy1_x1;
			}

			// Buttons 5 and 6 False
			if(joy1Btn(05) == 1 && joy1Btn(06) == 0)
			{
				motor[omnitr] = 127;
				motor[omnibr] = 127;
				motor[omnitl] = 127;
				motor[omnibl] = 127;
			}

			// Buttons 5 and 6 True
			if(joy1Btn(05) == 0 && joy1Btn(06) == 1)
			{
				motor[omnitr] = -127;
				motor[omnibr] = -127;
				motor[omnitl] = -127;
				motor[omnibl] = -127;
			}

			// Joy1_y2
		  if (joystick.joy1_y2 > 10)
		  {
		  	motor[omnitl] = -joystick.joy1_y2;
		  	motor[omnibr] = joystick.joy1_y2;
		  }
		  else if (joystick.joy1_y2 < -10)
		  {
		  	motor[omnitl] = -joystick.joy1_y2;
		  	motor[omnibr] = joystick.joy1_y2;
		  }

		  // Joy1_x2
			else if (joystick.joy1_x2 > 10)
			{
				motor[omnibl] = -joystick.joy1_x2;
				motor[omnitr] = joystick.joy1_x2; //if you can find this good for you - S3b4ss
			}
			else if (joystick.joy1_x2 < -10)
			{
				motor[omnibl] = -joystick.joy1_x2;
				motor[omnitr] = joystick.joy1_x2;
			}

	} // if base_servos < 50 close

			else
			{ // Tank drive when base_servos > 50

	      if (joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10)
				{
					motor[omnitr] = 0;
					motor[omnibr] = 0;
				}
				else
				{
					motor[omnitr] = -joystick.joy1_y1;
					motor[omnibr] = -joystick.joy1_y1;
				}
				if (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)
				{
					motor[omnitl] = 0;
					motor[omnibl] = 0;
				}
				else
				{
					motor[omnitl] = joystick.joy1_y2;
					motor[omnibl] = joystick.joy1_y2;
				}

	} // close else statement when base_servos > 50

			// Button 4 True and Button 3 False
	  	if (joy1Btn(04) == 1 && joy1Btn(03) == 0)
			{
				base_servos += 5;
			}
			// Button 3 True and Button 4 False
			else if (joy1Btn(03) == 1 && joy1Btn(04) == 0)
			{
				base_servos -= 5;
			}
			// Arm Door (d) and Arm Scoop (s)
     if(joystick.joy2_y1 < 10 && joystick.joy2_y1 > -10)
     {
       s += 0;
     }
     else
     {
       s += joystick.joy2_y1 / 10;
     }
     if (joystick.joy2_y2 < 10 && joystick.joy2_y2 > -10)
     {
       d += 0;
     }
     else
     {
       d += joystick.joy2_y2 / 10;
     }
     if(joystick.joy2_x1 < 10 && joystick.joy2_x1 > -10)
     {
       motor[raising] = 0;
     }
     else
     {
       motor[raising] = joystick.joy2_x1;
    }
     // TRUNK
     if(joy2Btn(1) == 1)
     {
       motor[trunk] = 100;
     }
     else if(joy2Btn(1) == 0)
     {
       motor[trunk] = 0;
     }
     else if(joy2Btn(2) == 1)
     {
       motor[trunk] = -100;
     }
     else if(joy2Btn(2) == 0)
     {
       motor[trunk] = 0;
     }

     // ROLLING GOAL GRABBING MECHANISM
     if (joy1Btn(7) == 1)
     {
       rg_left = 5;
     }
     if (joy1Btn(8) == 1)
     {
       rg_right = 5;
     }

			// Check range base_servos
			if (base_servos < 0)
			base_servos = 0;
			else if(base_servos > 256)
			base_servos = 256;
			if (s < 0)
			s = 0;
			else if(s > 256)
			s = 256;
			if (rg_left < 0)
			rg_left = 0;
			else if(rg_left > 256)
			rg_left = 256;
			if (rg_right < 0)
			rg_right = 0;
			else if(rg_right > 256)
			rg_right = 256;


			// Int declaration
			servo[dtbl] = (int) base_servos;
			servo[dtbr] = (int) base_servos;
			servo[arm_scoop] = (int) s;
			//servo[rg1] = (int) rg_left;
			//servo[rg2] = (int) rg_right;

		} // Close while (true) loop

} // Close task main()
