#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     finbas,         sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     stop,           sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     backleft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     frontleft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lifter,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     backright,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     frontright,    tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    conv,                 tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#define FORWARD_DIRECTION      1
#define BACKWARDS_DIRECTION   -1
#define STOP                   0

float convv;
void runAllMotors( int speed );
void stopAllMotors();
void runConveyorBelt( byte direction );
void turnLeft( int delta );
void turnRight( int delta );
int basket;

void initializeRobot()
{
	return;
}
task main()
{
	initializeRobot();
	waitForStart();
	convv = 0;
	basket = 0;

	runAllMotors( 50 );
	wait1Msec(550);
	stopAllMotors();
	wait1Msec(500);

	if (SensorValue[finbas] == 5)
	  {
		   basket = 1;
	  }
	 else if (SensorValue[finbas] != 5)
	    {
		    runAllMotors( 50 );
		    wait1Msec(300);
		    stopAllMotors();
	    }
	if (SensorValue[finbas] == 5)
	  {
		   basket = 2;
	  }
	 else if (SensorValue[finbas] != 5)
	    {
		    runAllMotors( 50 );
		    wait1Msec(300);
		    stopAllMotors();
	    }
	if (SensorValue[finbas] == 5)
	  {
	   	basket = 3;
	  }
	 else if (SensorValue[finbas] != 5)
	    {
		    runAllMotors( 50 );
		    wait1Msec(300);
		    stopAllMotors();
	    }
	if (SensorValue[finbas] == 5)
	  {
	   	basket = 4;
	  }
	 else if (SensorValue[finbas] != 5)
	    {
		    runAllMotors( 50 );
		    wait1Msec(300);
		    stopAllMotors();
	    }
	if (basket == 1)
	  {
		   turnRight( 50 );
		   wait1Msec(200);
		   stopAllMotors();
		   wait1Msec(300);
		   runAllMotors( 50 );
		   wait1Msec(300);
		   stopAllMotors();
		   wait1Msec(300);
		   runConveyorBelt( FORWARD_DIRECTION );
		   wait1Msec(600);
		   runConveyorBelt( BACKWARDS_DIRECTION );
		   wait1Msec(600);
		   runAllMotors( -50 );
		   wait1Msec(600);
		   stopAllMotors();
		   wait1Msec(300);
	  }
	if (basket == 2)
	{

	}

}

  /* End of Autonomous
   * Beginning of writing functions*/


  /*First function*/

void runAllMotors( int speed )
{
	/* Make sure that we don't overflow */
	if( speed > 127 )
		speed = 127;
  else if( speed < -127 )
  	speed = -127;

  /* Set motor speed */
	motor[backright] = speed;
  motor[frontright] = speed;
  motor[backleft] = speed;
  motor[frontleft] = speed;
}


  /*Second function*/

void stopAllMotors()
{
	runAllMotors(0); //set all motor power values to 0
}


  /*Third function*/

void runConveyorBelt( byte direction )
{
	if(direction == FORWARD_DIRECTION)
		servo[conv] = (int) 200; // pick any value from 128 to 255
	else if( direction == BACKWARDS_DIRECTION)
		servo[conv] = (int) 100; // pick any value from 0 to 127
  else if( direction == STOP)
    servo[conv] = (int) 127;
  else
  	servo[conv] = 127; //127 stops servo
}


  /*Fourth function*/

void turnLeft( int delta )
{
	motor[backleft] -= delta;
	motor[backright] += delta;
	motor[frontleft] -= delta;
	motor[frontright] += delta;

}


  /*Fifth function*/

void turnRight( int delta )
{
	motor[backleft] += delta;
	motor[backright] -= delta;
	motor[frontleft] += delta;
	motor[frontright] -= delta;
}

/*Sixth function*/

void iBasket ()
{

}
