#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     FL,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     BL,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     FR,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     BR,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"
task main()
{
				while(true)
				{
				getJoystickSettings(joystick);
				if(joystick.joy1_TopHat == -1 && joy1Btn(5) == 0 && joy1Btn(6) == 0)
				{
					motor[FL] = 0;
					motor[BL] = 0;
					motor[FR] = 0;
					motor[BR] = 0;
				}
				else if(joystick.joy1_TopHat == 0)
				{
					motor[FL] = -100;
					motor[BL] = -100;
					motor[FR] = 100;
					motor[BR] = 100;
				}
				else if(joystick.joy1_TopHat == 4)
				{
					motor[FL] = 100;
					motor[BL] = 100;
					motor[FR] = -100;
					motor[BR] = -100;
				}
				else if(joystick.joy1_TopHat == 2)
				{
					motor[FL] = -100;
					motor[BL] = 100;
					motor[FR] = -100;
					motor[BR] = 100;
				}
				else if(joystick.joy1_TopHat == 6)
				{
					motor[FL] = 100;
					motor[BL] = -100;
					motor[FR] = 100;
					motor[BR] = -100;
				}
				else if(joy1Btn(5) == 1)
				{
					motor[FL] = 100;
					motor[BL] = 100;
					motor[FR] = 100;
					motor[BR] = 100;
				}
				else if(joy1Btn(6) == 1)
				{
					motor[FL] = -100;
					motor[BL] = -100;
					motor[FR] = -100;
					motor[BR] = -100;
				}
				else if(joystick.joy1_TopHat == 1)
				{
					motor[FL] = -100;
					motor[BL] = 0;
					motor[FR] = 0;
					motor[BR] = 100;
				}
				else if(joystick.joy1_TopHat == 3)
				{
					motor[FL] = 0;
					motor[BL] = 100;
					motor[FR] = -100;
					motor[BR] = 0;
				}
				else if(joystick.joy1_TopHat == 5)
				{
					motor[FL] = 100;
					motor[BL] = 0;
					motor[FR] = 0;
					motor[BR] = -100;
				}
				else if(joystick.joy1_TopHat == 7)
				{
					motor[FL] = 0;
					motor[BL] = -100;
					motor[FR] = 100;
					motor[BR] = 0;
				}






			}
}
