#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     FrontLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     BackLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     FrontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     BackRight,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"
task main()
{
    getJoystickSettings (joystick);


    if (joystick.joy1_y1 > -10 && joystick.joy1_y1 < 10)
    {
    		motor [FrontRight] = 0;
    		motor [BackRight] = 0;
  	}
  	if (joystick.joy1_y2 > -10 && joystick.joy1_y2 < 10)
  	{
  		motor [FrontLeft] = 0;
  		motor [BackLeft] = 0;
    }


    if (joystick.joy1_y1 < -10 && joystick.joy1_y1 > 10)
    {
    	motor [FrontRight] = joystick.joy1_y1;
    	motor [FrontLeft] = joystick.joy1_y1;
    }

}
