 qqqqqqqqqqqqqqqqqqqqqqqqqqqqq`	```````````````````````````````````````````````#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     RightWheel,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     LeftWheel,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     Lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    Hook,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    Scoopturn,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"
task main()
{

		while (true)
  	{
				getJoystickSettings(joystick);



  	if (joystick.joy1_y1 > -10 && joystick.joy1_y1 < 10) //Left side wheels with left joystick controller 1
  	{
  			motor [LeftWheel] = 0;
    }

 		else
 		{
 				motor [LeftWheel] = joystick.joy1_y1;
 	  }



 	 if (joystick.joy1_y2 > -10 && joystick.joy1_y2 < 10) //right side wheels with right joystick controller 1
 		{
 				motor [RightWheel] = 0;
 	  }
 	 else
 	  {
 	   		motor [RightWheel] = joystick.joy1_y2;
 	  }



 	 /*if (joystick.joy2_y1 > -10 && joystick.joy1_y2 < 10) //Linear slide with left joystick controller 2
 	 {
 			 motor [Lift] = 0;
 	 }
 		else
 		{
 				motor [Lift] = joystick.joy2_y1;
 	  }
*/


 	  if (joy2Btn(4) == 0 && joy2Btn(2) == 1) //Scoop turn with button 4 controller 2
 	  {
 				servo [Scoopturn] = 0;
 	  }
 	  else if (joy2Btn(4) == 1 && joy2Btn(2) == 0)
 	  {
 	  		servo [Scoopturn] = 255;
 	  }
 	  else
 	  {
 	  		servo[Scoopturn] = 127;
 	  }

/*
 	  if (joy2Btn(2) == 0) // scoopturn backwards with button 2 controller 2
 	  {
 	  		servo [Scoopturn] = 127;
 	  }
 	  else if (joy2Btn (1) == 1)
 	  {
 	  		servo [Scoopturn] = 255;
 		}
*/
 	  if (joy2Btn(3) == 0) // Hook with button 3 controller 2
 	  {
 	  		servo [Hook] = 0;
 		}
 		else if (joy2Btn(3) == 1)
 		{
 				servo [Hook] = 255;
 		}


 	  /*if (joystick.joy2_y2 > -10 && joystick.joy2_y2 < 10) // Move scoop with joystick 2 controller 2
 	  {
 	  		servo [Scoop] = 0;
 		}
 	  else
 	  {
 	  		servo [Scoop] = joystick.joy2_y2; ignore this stuff because it's not necessary
 		} */
}

 	}
