#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     FrontLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     BackLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     FrontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     BackRight,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "joystickdriver.c"
task main()
{
	while (true)
		{
			getJoystickSettings(joystick);

if (joystick.joy1_y1 > -10 && joystick.joy1_y1 < 10)
		{
				motor [FrontLeft] = 0;
				motor [BackLeft] = 0;
				motor [FrontRight] = 0;
				motor [BackRight] = 0;
		}

else if






}






}
