#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     Sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     omnibr,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     omnitr,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     raising,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     raising2,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     omnibl,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     trunk,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     omnitl,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    rg1,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    dtbr,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    rg2,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    arm_scoop,            tServoStandard)
#pragma config(Servo,  srvo_S2_C3_1,    rg3,                  tServoStandard)
#pragma config(Servo,  srvo_S2_C3_2,    dtbl,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C3_3,    door,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C3_4,    claw,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C3_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C3_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// PURPOSE: OFFICIAL AUTONOMOUS FOR BAE :)
#include "joystickdriver.c"

void rotate ( int speed );
void runAllMotors ( int speed );
void runAllRight ( int speed );
void rise ( int speed );
float nickfeet = 30;
int ref = 0;
int ref2 = 0;
bool score = false;


task main()
{
	waitForStart();
	servo[rg2] = 127;
	servo[dtbr] = 0;
	servo[dtbl] = 0;


/*
	//Initializing claw
	motor[raising] = 100;
	motor[raising2] = 100;
	wait1Msec(3300);
	motor[raising] = 0;
	motor[raising2] = 0;
	wait1Msec(300);
	motor[trunk] = 100;
	wait1Msec(1600);
	motor[trunk] = 0;
	wait1Msec(400);
	motor[raising] = -100;
	motor[raising2] = -100;
	wait1Msec(2500);
	motor[raising] = 0;
	motor[raising2] = 0;
	wait1Msec(700);

	//scoring on ir basket
	runAllMotors(-100);
	wait1Msec(1200);
	rotate(0);

	wait1Msec(1000);


	runAllRight(100);
	wait1Msec(1000);
	rotate(0);
	wait1Msec(1000);

	runAllRight(-100);
	while(SensorValue[IR] != 5 && score == false)
	{
		wait1Msec(10);
	}
	rotate(0);

	wait1Msec(300);
	runAllRight(100);
	wait1Msec(250);
	rotate(0);

	wait1Msec(300);
	runAllMotors(-100);
	wait1Msec(250);
	rotate(0);
	wait1Msec(300);

	servo[door] = 0;
	wait1Msec(1000);

	wait1Msec(300);
	motor[trunk] = -50;
	wait1Msec(500);
	motor[trunk] = 50;
	wait1Msec(500);
	motor[trunk] = 0;
	wait1Msec(500);

	runAllMotors(100);
	wait1Msec(250);
	rotate(0);
	*/
	runAllRight(-100);
	while(SensorValue[Sonar] <= (4*nickfeet))
	{
	 wait1Msec(600);
	}
	rotate(0);










	}






void rotate ( int speed )
{
	motor[omnitl] = speed;
	motor[omnitr] = speed;
	motor[omnibl] = speed;
	motor[omnibr] = speed;
}
void runAllMotors( int speed )
{
	if (speed > 127)
		speed = 127;
	else if( speed < -127)
		speed = -127;

		motor[omnitr] = speed;
		motor[omnibr] = speed;
		motor[omnibl] = -speed;
		motor[omnitl] = -speed;
}
void runAllRight( int speed ) // Horizontal DIR
{
	motor[omnitr] = -speed;
	motor[omnibr] = speed;
	motor[omnitl] = -speed;
	motor[omnibl] = speed;
}
void rise( int speed )
{
	motor[raising] = speed;
	wait1Msec(400);
	motor[raising] = 0;
	while (ref2 > 40)
	{
		servo[claw] = 255;
		servo[door] = 255;
		wait1Msec(10);
		ref2++;
	}

	runAllMotors(0);
	wait1Msec(500);
}
