#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     bright,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,    left,               tServoStandard)
#pragma config(Motor,  mtr_S1_C2_2,    bleft,               tServoNone)
#pragma config(Motor,  mtr_S1_C2_3,    conv,               tServoNone)
#pragma config(Motor,  mtr_S1_C2_4,    flag,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c" // Tells ROBOTC to include the driver file for the joysti ck.

task main()   //the decimals gives us more precise controll
{
	while (true)
  {
  	//wheels
    getJoystickSettings(joystick); // Updates Buttons and Joysticks

    if (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)  /* Makes left side wheels move in tandem and same speed */
    {																											// Makes motors = joystick move
    																											//	but if at 10 or negative 10 stop
      motor[bright] = 0;  // just states if joystick = 10 or -10 motor = 0
      motor[right] = 0;

    }
    else
    {

    	motor[bright] = joystick.joy1_y2;
			motor[right] = joystick.joy1_y2; // if it is above 10 or -10 then the motor power = the joystick.

    }

    if (joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10)  /* Makes left side wheels move in tandem and same speed */
    {																											// Makes motors = joystick move
    																											//	but if at 10 or negative 10 stop
      motor[bleft] = 0; // joystick if 10 or -10 = motor power = 0
      motor[left] = 0;

    }
    else
    {

      motor[bleft] = joystick.joy1_y1;  // if it is above 10 or -10 then the motor power = the joystick.
      motor[left] = joystick.joy1_y1;

    }
    //conveyor belt
      if (joystick.joy2_y1 < 10 && joystick.joy2_y1 > -10)
    {

      motor[conv] = 0;

    }
    else
    {

      motor[conv] = joystick.joy2_y1;

    }
    	//flag
    if (joystick.joy2_y2 < 10 && joystick.joy2_y2 > -10)
    {
      motor[flag] = 0;
    }
    else
    {
      motor[flag] = joystick.joy2_y2;
    }

    }
}
