#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Backleft,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Backright,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Frontleft,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Frontright,    tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"

task main ()
{
  while true
{
 if (joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10)
 {
   motor[Backleft]=0;
   motor[Frontleft]=0;
 }
 else
 {
   motor[Backright]=joystick.joy1_y1;
   motor[Frontright]=joystick.joy1_y1;
 }
 if (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)
 {
   motor[Backright]=0;
   motor[Frontright]=0;
 }
 else
 {
   motor[Backright]=joystick.joy1_y2;
   motor[Frontright]=joystick.joy1_y2;
 }
 if joy1btn(1)==1
 {
   motor[Backright]=10;
   motor[Frontright]=10;
 }
 if joy1btn(2)==1
 {
   motor[Backleft]10;
   motor[Frontleft]=10;
 }











}
}
