#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     frontright,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     backright,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     frontleft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     backleft,      tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"
task main()
{

while(true)

{
if (joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10) //Right joystick moves back and front right wheels
		{
			motor[backright] = 0;
			motor[frontright] = 0;
		}
		else
	  {
	  	motor[backright] = (joystick.joy1_y1);
	  	motor[frontright] = (joystick.joy1_y1);
	  }
  	if (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10) //Left joystick moves back and front left wheels
  	{
	  	motor[backleft] = 0;
	  	motor[frontleft] = 0;
  	}
  	else
  	{
  		motor[backleft] = (joystick.joy1_y2);
  		motor[frontleft] = (joystick.joy1_y2);
  	}
   }
}
