#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motor2,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motor1,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"

task main()
{
while (true)
{
	getJoystickSettings(joystick);



if (joystick.joy1_y1 > -10 && joystick.joy1_y1 < 10)
{
	motor[motor1] = 0;
}
 else
 {
   motor[motor1] = joystick.joy1_y1;
 }
 if(joystick.joy1_y2 > -10 && joystick.joy1_y2 < 10)
 {
   motor[motor2] = 0;
}
 else
 {
   motor[motor2] = joystick.joy1_y2;
 }

}
}
