#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     turnSensor,     sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     omnitl,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     omnibl,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     omnitr,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     omnibr,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"
task main()
{
	while(true)
	{
		getJoystickSettings(joystick);
		if (joystick.joy1_x2 < 10 && joystick.joy1_x2 > -10 && joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10 && joystick.joy1_x1 < 10 && joystick.joy1_x1 > -10 && joy1Btn(06) == 0 && joy1Btn(05)== 0 && joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)
				{
				  motor[omnitl] = 0;
			    motor[omnibl] = 0;
			    motor[omnitr] = 0;
			    motor[omnibr] = 0;
			  }

			// Joy1_y1
			if (joystick.joy1_y1 > 10)
			{
				motor[omnitl] = -joystick.joy1_y1;
			  motor[omnibl] = -joystick.joy1_y1;
			  motor[omnitr] = joystick.joy1_y1;
			  motor[omnibr] = joystick.joy1_y1;
			}
			else if(joystick.joy1_y1 < -10)
			{
				motor[omnitl] = -joystick.joy1_y1;
				motor[omnibl] = -joystick.joy1_y1;
				motor[omnitr] = joystick.joy1_y1;
				motor[omnibr] = joystick.joy1_y1;
			}

			// Joy1_x1
			else if (joystick.joy1_x1 > 10)
			{
				motor[omnitr] = -joystick.joy1_x1;
				motor[omnibr] = joystick.joy1_x1;
				motor[omnitl] = -joystick.joy1_x1;
				motor[omnibl] = joystick.joy1_x1;
			}
			else if (joystick.joy1_x1 < -10)
			{
				motor[omnitr] = -joystick.joy1_x1;
				motor[omnibr] = joystick.joy1_x1;
				motor[omnitl] = -joystick.joy1_x1;
				motor[omnibl] = joystick.joy1_x1;
			}

			// Buttons 5 and 6 False
			if(joy1Btn(05) == 1 && joy1Btn(06) == 0)
			{
				motor[omnitr] = 127;
				motor[omnibr] = 127;
				motor[omnitl] = 127;
				motor[omnibl] = 127;
			}

			// Buttons 5 and 6 True
			if(joy1Btn(05) == 0 && joy1Btn(06) == 1)
			{
				motor[omnitr] = -127;
				motor[omnibr] = -127;
				motor[omnitl] = -127;
				motor[omnibl] = -127;
			}

			// Joy1_y2
		  if (joystick.joy1_y2 > 10)
		  {
		  	motor[omnitl] = -joystick.joy1_y2;
		  	motor[omnibr] = joystick.joy1_y2;
		  }
		  else if (joystick.joy1_y2 < -10)
		  {
		  	motor[omnitl] = -joystick.joy1_y2;
		  	motor[omnibr] = joystick.joy1_y2;
		  }

		  // Joy1_x2
			else if (joystick.joy1_x2 > 10)
			{
				motor[omnibl] = -joystick.joy1_x2;
				motor[omnitr] = joystick.joy1_x2; //if you can find this good for you - S3b4ss
			}
			else if (joystick.joy1_x2 < -10)
			{
				motor[omnibl] = -joystick.joy1_x2;
				motor[omnitr] = joystick.joy1_x2;
			}
} //End While true
} //End Task main
