#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Backleft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Frontleft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Backright,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Frontright,    tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    Trans1,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_2,    Trans2,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_3,    Clam,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
float claw_m;
float t_1;
float t_2;

task main()
{
claw_m = 0;
t_1 = 0;
t_2 = 0;
while(true)
{
getJoystickSettings(joystick);

    if(joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10)
    {
      motor[Backleft] = 0;
      motor[Frontleft] = 0;
    }

    else
    {
	    motor[Backleft] = joystick.joy1_y1;
	    motor[Frontleft] = joystick.joy1_y1;
    }

    if(joystick.joy1_y2 < 10 && joystick.joy1_y2 > - 10)
    {
      motor[Backright] = 0;
      motor[Frontright] = 0;
    }

    else
    {
      motor[Backright] = joystick.joy1_y2;
      motor[Frontright] = joystick.joy1_y2;
    }

    //Claw
    if(joy1Btn(7) == 1)
    {
	    claw_m += 1;
    }

    else if(joy1Btn(8) == 1)
    {
	    claw_m -= 1;
    }

    //check range
    if (claw_m < 0)
        claw_m = 10;
    else if (claw_m > 255)
        claw_m = 245;

    //int
    servo[Clam] = (int) claw_m;

    //Transformer
    if(joy2Btn(7) == 1)
    {
    	servo[Trans1] = 200;
    	servo[Trans2] = 200;
    }

    else if(joy2Btn(8) == 1)
    {
    	servo[Trans1] = 100;
    	servo[Trans2] = 100;
    }

    //int
    servo[Trans1] = (int) t_1;
    servo[Trans2] = (int) t_2;


    //Check Range
    if (t_1 < 0)
    	  t_1 = 10;
    else if (t_1 > 255)
    	  t_1 = 245;
    if (t_2 < 0)
    	  t_2 = 10;
    else if (t_2 > 255)
    	  t_2 = 245;

   }

}
