#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     infrared,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C4_1,     bas,           tmotorTetrix, openLoop)// fix
#pragma config(Motor,  mtr_S1_C3_1,     r,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     l,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_1,     lift_down,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     lift_up,           tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"

//Purpose: new autonomous for sophomore robot
void forward(int speed);
void stopM();
void rotate(int speed, int time);
void move(int speed, int time);
void rotation(int speed);
void lift(int speed, int time);

task main()
{
	waitForStart();
	lift(100,1500);
	move(100,2000);
	motor[bas] = -20;
  wait1Msec(1000);
  motor[bas] = 20;
  wait1Msec(2000);
	move(-100,200);
	//lift
	motor[lift_down] = 100;
	wait1Msec(1500);
	motor[lift_down] = 0;
	//end lift
	rotate(50,1000);
	move(100,1000);
	rotate(-50,1000);
	move(100,3000);

}

 move(int speed, int time)
{
forward(speed);
wait1Msec(time);
stopM();
}

void rotate(int speed, int time)
{
	rotation
	(speed);
	wait1Msec(time);
	stopM();
}
void rotation(int speed) // (+CW) (-CCW)
{
	motor[l] = speed;
	motor[r] = -speed;
}

void forward(int speed)
{
	motor[l] = speed;
	motor[r] = speed;
}

void lift(int speed, int time)
{
	motor[lift_up] = speed;
	wait1Msec(time);
	motor[lift_up] = 0;
}
void stopM()
{
 forward(0);
}
