#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     FL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     BL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     FR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BR,            tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    claw,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c";

float clawv;
task main()
{
	while(true)
	{
	getJoystickSettings(joystick);

	if(joystick.joy1_y1 > -10 && joystick.joy1_y1 < 10)
	{
		motor[FL] = 0;
		motor[BL] = 0;
	}
	else
	{
		motor[FL] = joystick.joy1_y1;
		motor[BL] = joystick.joy1_y1;
  }

  if(joystick.joy1_y2 > -10 && joystick.joy1_y2 < 10)
  {
  	motor[FR] = 0;
  	motor[BR] = 0;
  }
  else
  {
  	motor[FR] = joystick.joy1_y2;
  	motor[BR] = joystick.joy1_y2;
  }

  if(joy1Btn(1) == 1 && joy1Btn(4) == 0)
{
clawv -= .5;
}
else if(joy1Btn(1) == 0 && joy1Btn(4) == 1)
{
clawv += .5;
}




if(clawv > 255)
	clawv = 255;
else if(clawv < 0)
	clawv = 0;



	servo[claw] = (int)clawv;

}

	}
