#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     lift,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    claw,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    claw2,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"

task main()
{
float clawv = 255;
float claw2v = 255;
while(true)
{
if( joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10)
{
	motor[left] = 0;
}
else
{
	motor[left] = joystick.joy1_y1;
}
if( joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)
{
	motor[right] = 0;
}
else
{
	motor[right] = joystick.joy1_y2;
}


if(joy1Btn(3) == 1 && joy1Btn(2) == 0)
{
	motor[lift] = 100;
}
else if(joy1Btn(2) == 1 && joy1Btn(3) == 0)
{
	motor[lift] = -100;
}
else
{
motor[lift] = 0;
}




if(joy1Btn(1) == 1 && joy1Btn(4) == 0)
{
clawv -= .5;
}
else if(joy1Btn(1) == 0 && joy1Btn(4) == 1)
{
clawv += .5;
}



if(joy1Btn(1) == 1 && joy1Btn(4) == 0)
{
	claw2v -= .5;
}
else if(joy1Btn(1) == 0 && joy1Btn(4) == 1)
{
	claw2v += .5;
}



if(clawv > 255)
	clawv = 255;
else if(clawv < 0)
	clawv = 0;

if(claw2v > 255)
	claw2v = 255;
else if(claw2v < 0)
	claw2v = 0;

	servo[claw] = (int)clawv;
	servo[claw2] = (int)claw2v;
}
}
