#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     sright,         sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     backleft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     frontleft,     tmotorTetrix, openLoop,)
#pragma config(Motor,  mtr_S1_C2_1,     backright,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     frontright,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     linear,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    loc,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    cube,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"
float pullup_lock;
float cub3;
task main()
{
	pullup_lock = 255;
	cub3 = 0;
	int x = 1;
	while(true)
	{
		getJoystickSettings(joystick);

		//	Wheels
    if (joy1Btn(8) == 1)
    {
      x = 4;     //we divided the joystick value by x to controll the speed when rasing the flag
    }
    else
    {
      x = 1;
    }
		if (joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10) //Right joystick moves back and front right wheels
		{
			motor[backleft] = 0;
			motor[frontleft] = 0;
		}
		else
	  {
	  	motor[backleft] = (joystick.joy1_y1)/x;
	  	motor[frontleft] = (joystick.joy1_y1)/x;
	  }
  	if (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10) //Left joystick moves back and front left wheels
  	{
	  	motor[backright] = 0;
	  	motor[frontright] = 0;
  	}
  	else
  	{
  		motor[backright] = (joystick.joy1_y2)/x;
  		motor[frontright] = (joystick.joy1_y2)/x;
  	}

  	//Flag

  	if (joystick.joy2_y1 < 10 && joystick.joy2_y1 > -10)
  	{
  		motor[flag] = 0;
  	}
  	else
  	{
  		motor[flag] = joystick.joy2_y1;
  	}

  	//Linear

  	if (joystick.joy2_y2 < 10 && joystick.joy2_y2 > -10)
  	{
  		motor[linear] = 0;
  	}
  	else
  	{
  		motor[linear] = joystick.joy2_y2;
  	}

  	//pull-up lock

	  if  (joy2Btn(5) == 1)
  	{
  		pullup_lock += 1;
  	}

	  else if	(joy2Btn(6) == 1)
    {
    	pullup_lock -= 1;
    }


  	//Check Range
  	if (pullup_lock < 0)
    pullup_lock = 0;
    else if(pullup_lock > 255)
    pullup_lock = 255;

    //Int servos
   	servo[loc] = (int) pullup_lock;
   	servo[cube] = (int) cub3;


   	//cube

   	if  (joy2Btn(1) == 1)
  	{
  		cub3 += 1;
  	}

	  else if	(joy2Btn(2) == 1)
    {
    	cub3 -= 1;
    }

    //Check Range
  	if (cub3 < 0)
    cub3 = 0;
    else if(cub3 > 255)
    cub3 = 255;

   }
}
