#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     infrared,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     FL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     BL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     FR,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     BR,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     arm,           tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     flag,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"

void forward(int speed);
void stopM();
void rotate(int speed);
void move(int speed, int time);
void rotation(int speed, int time);
void lift(int speed, int time, int speedc);



task main()
{
	waitForStart();
	//wait1Msec(5500);
	forward(50);
	wait1Msec(6000);

	/*while(SensorValue[infrared] != 5)
	{
		wait10Msec(5);
	}
	stopM();

	forward(50);
	while(SensorValue[touch] != 1)
	{
		wait10Msec(1);
	}
	stopM();*/

}//end main

void move(int speed, int time)
{
forward(speed);
wait1Msec(time);
stopM();
}

void rotation(int speed, int time)
{
	rotate(speed);
	wait1Msec(time);
	stopM();
}

void rotate(int speed) // (+CW) (-CCW)
{
	motor[FL] = speed;
	motor[BL] = speed;
	motor[FR] = -speed;
	motor[BR] = -speed;
}

void forward(int speed)
{
	motor[FL] = speed;
	motor[BL] = speed;
	motor[FR] = speed;
	motor[BR] = speed;
}

void lift(int speed, int time, int speedc)
{
	motor[arm] = speed;
	wait1Msec(time);
	motor[arm] = speedc;
}

void stopM()
{
 forward(0);
}
