#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     FL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     BL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     FR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     BR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     arm,           tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     spin,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    winch,                tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//#pragma config(Servo,  srvo_S2_C1_1,    scoop,                tServoContinuousRotation)

#include "joystickdriver.c";
task main()
{
	int winchv = 0;
	//float scoopc = 255;

	while(true)
	{
	if(joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10)
	{
		motor[FL] = 0;
		motor[BL] = 0;
	}
	else
	{
		motor[FL] = (joystick.joy1_y1);
		motor[BL] = (joystick.joy1_y1);
	}

	if(joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)
	{
		motor[FR] = 0;
		motor[BR] = 0;
	}
	else
	{
		motor[FR] = (joystick.joy1_y2);
		motor[BR] = (joystick.joy1_y2);
	}

	/*lift Joystick 2*/
	if(joy2Btn(6) == 1 && joy2Btn(5) == 0)
	{
		motor[arm] = 50;
	}
	else if(joy2Btn(5) == 1 && joy2Btn(6) == 0)
	{
		motor[arm] = -50;
	}
	else
	{
		motor[arm] = 0;
	}

	/*flag Joystick 1*/
	if(joy1Btn(2) == 1 && joy1Btn(3) == 0)
	{
		motor[flag] = 100;
	}
	else if(joy1Btn(3) == 1 && joy1Btn(2) == 0)
	{
		motor[flag] = -100;
	}
	else
	{
		motor[flag] = 0;
	}

	/*spin Joystick 2*/
	if(joy2Btn(1) == 1 && joy2Btn(4) == 0)
	{
		motor[spin] = 100;
	}
	else if(joy2Btn(4) == 1 && joy2Btn(1) == 0)
	{
		motor[spin] = -100;
	}
	else
	{
	  motor[spin] = 0;
	}

	/* hook Joystick 2 */
	/*if(joy2Btn(2) == 1 && joy2Btn(3) == 0)
	{
		scoopc -= .5;
	}
	else if(joy2Btn(3) == 1 && joy2Btn(2) == 0)
	{
		scoopc += .5;
	}

	servo[scoop] = (int)scoopc;*/


/*if( joy2Btn(7) == 1 && winchv == 0)
{
	winchv = 1;
	servo[winch] = 245;
}
else if(joy2Btn(7) == 0 && winchv == 1)
{
	winchv = 2;
}
else if(joy2Btn(7) == 1 && winchv == 2)
{
	winchv = 3;
	servo[winch] = 270;
}
else if(joy2Btn(7) == 0 && winchv == 3)
{
	winchv = 0;
}*/


}
}
